/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.almeneses.exam.server.ui;

/**
 *
 * @author alejo
 */
public class ServerUI extends javax.swing.JFrame {

        /**
         * Creates new form ServerUI
         */
        public ServerUI() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                bgPanel = new javax.swing.JPanel();
                actionsPanel = new javax.swing.JPanel();
                startExamBtn = new javax.swing.JButton();
                loadExamBtn = new javax.swing.JButton();
                generalInfoScrollPanel = new javax.swing.JScrollPane();
                generalInfoTextArea = new javax.swing.JTextArea();
                statusPanel = new javax.swing.JPanel();
                examStatusValueLabel = new javax.swing.JLabel();
                examStatusLabel = new javax.swing.JLabel();
                remainingTimeValueLabel = new javax.swing.JLabel();
                remainingTimeLabel = new javax.swing.JLabel();
                connectedScrollPane = new javax.swing.JScrollPane();
                connectedTextArea = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setName("Form"); // NOI18N

                bgPanel.setName("bgPanel"); // NOI18N

                actionsPanel.setName("actionsPanel"); // NOI18N

                startExamBtn.setText("Start Exam");
                startExamBtn.setName("startExamBtn"); // NOI18N

                loadExamBtn.setText("Load Exam");
                loadExamBtn.setName("loadExamBtn"); // NOI18N
                loadExamBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loadExamBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout actionsPanelLayout = new javax.swing.GroupLayout(actionsPanel);
                actionsPanel.setLayout(actionsPanelLayout);
                actionsPanelLayout.setHorizontalGroup(
                                actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(actionsPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(loadExamBtn,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                115, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(startExamBtn,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                115, Short.MAX_VALUE)));
                actionsPanelLayout.setVerticalGroup(
                                actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionsPanelLayout
                                                                .createSequentialGroup()
                                                                .addGap(0, 0, 0)
                                                                .addGroup(actionsPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.CENTER)
                                                                                .addComponent(loadExamBtn,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(startExamBtn,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                38, Short.MAX_VALUE))
                                                                .addContainerGap()));

                generalInfoScrollPanel.setName("generalInfoScrollPanel"); // NOI18N

                generalInfoTextArea.setColumns(20);
                generalInfoTextArea.setRows(5);
                generalInfoTextArea.setName("generalInfoTextArea"); // NOI18N
                generalInfoScrollPanel.setViewportView(generalInfoTextArea);

                statusPanel.setName("statusPanel"); // NOI18N

                examStatusValueLabel.setName("examStatusValueLabel"); // NOI18N

                examStatusLabel.setText("Exam status:");
                examStatusLabel.setName("examStatusLabel"); // NOI18N

                remainingTimeValueLabel.setName("remainingTimeValueLabel"); // NOI18N

                remainingTimeLabel.setText("Remaining time:");
                remainingTimeLabel.setName("remainingTimeLabel"); // NOI18N

                javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
                statusPanel.setLayout(statusPanelLayout);
                statusPanelLayout.setHorizontalGroup(
                                statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(statusPanelLayout.createSequentialGroup()
                                                                .addGroup(statusPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(statusPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(remainingTimeLabel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                100,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(remainingTimeValueLabel,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(statusPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(examStatusLabel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                84,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(examStatusValueLabel,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap()));
                statusPanelLayout.setVerticalGroup(
                                statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(statusPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(statusPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(examStatusLabel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(examStatusValueLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                17,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(statusPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(remainingTimeLabel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(remainingTimeValueLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                17,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));

                connectedScrollPane.setName("connectedScrollPane"); // NOI18N

                connectedTextArea.setEditable(false);
                connectedTextArea.setColumns(20);
                connectedTextArea.setRows(5);
                connectedTextArea.setName("connectedTextArea"); // NOI18N
                connectedScrollPane.setViewportView(connectedTextArea);

                javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
                bgPanel.setLayout(bgPanelLayout);
                bgPanelLayout.setHorizontalGroup(
                                bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout
                                                                .createSequentialGroup()
                                                                .addGroup(bgPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(bgPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(bgPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(actionsPanel,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                bgPanelLayout.createSequentialGroup()
                                                                                                                                                .addContainerGap()
                                                                                                                                                .addComponent(statusPanel,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                .addGap(80, 80, 80))
                                                                                .addGroup(bgPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(generalInfoScrollPanel)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addComponent(connectedScrollPane,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                160,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));
                bgPanelLayout.setVerticalGroup(
                                bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bgPanelLayout.createSequentialGroup()
                                                                .addGap(69, 69, 69)
                                                                .addComponent(actionsPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(bgPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(connectedScrollPane)
                                                                                .addComponent(generalInfoScrollPanel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                244, Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(statusPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(45, 45, 45)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void loadExamBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loadExamBtnActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_loadExamBtnActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JPanel actionsPanel;
        javax.swing.JPanel bgPanel;
        javax.swing.JScrollPane connectedScrollPane;
        javax.swing.JTextArea connectedTextArea;
        javax.swing.JLabel examStatusLabel;
        javax.swing.JLabel examStatusValueLabel;
        javax.swing.JScrollPane generalInfoScrollPanel;
        javax.swing.JTextArea generalInfoTextArea;
        javax.swing.JButton loadExamBtn;
        javax.swing.JLabel remainingTimeLabel;
        javax.swing.JLabel remainingTimeValueLabel;
        javax.swing.JButton startExamBtn;
        javax.swing.JPanel statusPanel;

        // End of variables declaration//GEN-END:variables
        public javax.swing.JPanel getActionsPanel() {
                return actionsPanel;
        }

        public void setActionsPanel(javax.swing.JPanel actionsPanel) {
                this.actionsPanel = actionsPanel;
        }

        public javax.swing.JPanel getBgPanel() {
                return bgPanel;
        }

        public void setBgPanel(javax.swing.JPanel bgPanel) {
                this.bgPanel = bgPanel;
        }

        public javax.swing.JLabel getExamStatusLabel() {
                return examStatusLabel;
        }

        public void setExamStatusLabel(javax.swing.JLabel examStatusLabel) {
                this.examStatusLabel = examStatusLabel;
        }

        public javax.swing.JLabel getExamStatusValueLabel() {
                return examStatusValueLabel;
        }

        public void setExamStatusValueLabel(javax.swing.JLabel examStatusValueLabel) {
                this.examStatusValueLabel = examStatusValueLabel;
        }

        public javax.swing.JScrollPane getGeneralInfoScrollPanel() {
                return generalInfoScrollPanel;
        }

        public void setGeneralInfoScrollPanel(javax.swing.JScrollPane generalInfoScrollPanel) {
                this.generalInfoScrollPanel = generalInfoScrollPanel;
        }

        public javax.swing.JTextArea getGeneralInfoTextArea() {
                return generalInfoTextArea;
        }

        public void setGeneralInfoTextArea(javax.swing.JTextArea generalInfoTextArea) {
                this.generalInfoTextArea = generalInfoTextArea;
        }

        public javax.swing.JButton getLoadExamBtn() {
                return loadExamBtn;
        }

        public void setLoadExamBtn(javax.swing.JButton loadExamBtn) {
                this.loadExamBtn = loadExamBtn;
        }

        public javax.swing.JLabel getRemainingTimeLabel() {
                return remainingTimeLabel;
        }

        public void setRemainingTimeLabel(javax.swing.JLabel remainingTimeLabel) {
                this.remainingTimeLabel = remainingTimeLabel;
        }

        public javax.swing.JLabel getRemainingTimeValueLabel() {
                return remainingTimeValueLabel;
        }

        public void setRemainingTimeValueLabel(javax.swing.JLabel remainingTimeValueLabel) {
                this.remainingTimeValueLabel = remainingTimeValueLabel;
        }

        public javax.swing.JButton getStartExamBtn() {
                return startExamBtn;
        }

        public void setStartExamBtn(javax.swing.JButton startExamBtn) {
                this.startExamBtn = startExamBtn;
        }

        public javax.swing.JPanel getStatusPanel() {
                return statusPanel;
        }

        public void setStatusPanel(javax.swing.JPanel statusPanel) {
                this.statusPanel = statusPanel;
        }

        public javax.swing.JScrollPane getConnectedScrollPane() {
                return connectedScrollPane;
        }

        public void setConnectedScrollPane(javax.swing.JScrollPane connectedScrollPane) {
                this.connectedScrollPane = connectedScrollPane;
        }

        public javax.swing.JTextArea getConnectedTextArea() {
                return connectedTextArea;
        }

        public void setConnectedTextArea(javax.swing.JTextArea connectedTextArea) {
                this.connectedTextArea = connectedTextArea;
        }

}
